### ISSUE TITLE
Failure to build with 0.8.0; correcting error results in successful build, but program crashes session

### ISSUE THREAD

**Issue by flexibeast** [soreau/wf-info#9]
Trying to build this in order to retrieve `app_id` values for use with the `window-rules` plugin, the build failed:
```
./src/plugin/wayfire-information.cpp:105:42: error: ‘wlr_xwayland_surface_try_from_wlr_surface’ was not declared in this scope; did you mean ‘wlr_xwayland_surface_from_wlr_surface’?
  105 |     is_xwayland_surface = wlr_surface && wlr_xwayland_surface_try_from_wlr_surface(wlr_surface);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          wlr_xwayland_surface_from_wlr_surface
ninja: build stopped: subcommand failed.
```
Indeed, removing `try_` from that line (and line 108) allows the build to complete successfully. However, running the resulting binary, e.g. `wf-info -l` or simply `wf-info`, crashes the entire Wayfire session.

**Comment by mrsteve0924** [comment]
im getting the same error.  i'll hold off on your build fix for now though.  i am on latest wayfire commit 481e2d2

**Comment by soreau** [comment]
Is this still happening with latest wf-info?

**Comment by flexibeast** [comment]
Hmm .... It builds and installs okay - i just cloned a fresh copy of the repo - but running it results in:
```
$ wf-info
Wayfire information protocol not advertised by compositor. Is wf-info plugin enabled?
```
and the `wf-info` plugin does seem to be enabled in my config. This is with 0.9.0, built from the Gentoo-provided ebuild, built (as far as i can tell by looking at [the ebuild file](https://github.com/gentoo/gentoo/blob/master/gui-wm/wayfire/wayfire-0.9.0.ebuild)) using wlroots 17.4 (although 18.0 recently got installed as well).

Perhaps i'm doing something wrong?

**Comment by soreau** [comment]
You can run `wayfire -d /tmp/wayfire.ini` where `wayfire.ini` has wf-info in [core] plugins. The debug output with `-d` should tell you if there was a problem loading wf-info plugin, or if it was successful. wf-info should be installed to the same prefix as wayfire. Did you pass `--prefix=/usr` when configuring with meson? If you did not specify a --prefix, the default is /usr/local/ and wayfire might be trying to load an old version.

**Comment by flexibeast** [comment]
> You can run wayfire -d /tmp/wayfire.ini where wayfire.ini has wf-info in [core] plugins. The debug output with -d should tell you if there was a problem loading wf-info plugin, or if it was successful.

The debug output has the lines:
```
DD 01-09-24 13:44:38.632 - [wayfire-0.9.0/src/core/plugin-loader.cpp:119] Loaded plugin /usr/lib64/wayfire/libwater.so
DD 01-09-24 13:44:38.633 - [wayfire-0.9.0/src/core/plugin-loader.cpp:119] Loaded plugin /usr/lib64/wayfire/libwf-info.so
DD 01-09-24 13:44:38.633 - [wayfire-0.9.0/src/core/plugin-loader.cpp:119] Loaded plugin /usr/lib64/wayfire/libwindow-rules.so
```

> wf-info should be installed to the same prefix as wayfire.

```
$ which wf-info 
/usr/bin/wf-info
$ which wayfire
/usr/bin/wayfire
```

> Did you pass --prefix=/usr when configuring with meson?

Yes.

> If you did not specify a --prefix, the default is /usr/local/ and wayfire might be trying to load an old version.

\*nod\* Fair point. However, i've not yet manually compiled Wayfire on this box (i.e. i've only ever compiled via the ebuild), which i've only had for a couple on months. i've confirmed that there's nothing in /usr/local/ via:

```
$ locate wayfire | grep '/local/'
$
```

**Comment by soreau** [comment]
If you run `ls -l /usr/bin/wf-info /usr/lib64/wayfire/libwf-info.so`, does it show the same date for each file and the date you expect, when you installed it last?

**Comment by flexibeast** [comment]
Yep, this is from my "clone, build and install" a couple of hours ago:
```
$ ls -l /usr/bin/wf-info /usr/lib64/wayfire/libwf-info.so                                       
-rwxr-xr-x 1 root root   94648 Sep  1 13:03 /usr/bin/wf-info*
-rwxr-xr-x 1 root root 1256696 Sep  1 13:03 /usr/lib64/wayfire/libwf-info.so*
```

**Comment by soreau** [comment]
Ok good. What is the output of `pkg-config --modversion wlroots`?

**Comment by flexibeast** [comment]
```
$ pkg-config --modversion wlroots                        
0.17.4
```

**Comment by soreau** [comment]
The only other thing I can think of is that you might need to restart wayfire.

**Comment by soreau** [comment]
Other things to try: Run `WAYLAND_DEBUG=1 wf-info` to get more information. See if the compositor is advertising `wf_info_base`. If it is and you still get the message with `wf-info`, try the qt gui python3 wf-info app [found in this repository](https://github.com/soreau/wf-info/blob/master/src/client/qt/gui.py).

**Comment by flexibeast** [comment]
So, restarting Wayfire made a difference; i no longer get that error message. Unfortunately, what now happens is that the session becomes unresponsive - there's no longer any pointer and nothing seems to have the focus or to accept input (although i can still switch between workspaces). Terminating the `wl-info` process from an VT didn't have any effect; the session remained unresponsive, and i had to terminate the `wayfire` process as well.

Running `wf-info` alone produced no output on the terminal, but running `WAYLAND_DEBUG=1 wf-info > out.txt 2>&1` resulted in (prior to me terminating the `wayfire` process):
```
[1185504.751] {Default Queue}  -> wl_display#1.get_registry(new id wl_registry#2)
[1185504.778] {Default Queue}  -> wl_display#1.sync(new id wl_callback#3)
[1185504.859] {Display Queue} wl_display#1.delete_id(3)
[1185504.865] {Default Queue} wl_registry#2.global(1, "wl_shm", 1)
[1185504.871] {Default Queue} wl_registry#2.global(2, "wl_drm", 2)
[1185504.875] {Default Queue} wl_registry#2.global(3, "zwp_linux_dmabuf_v1", 4)
[1185504.879] {Default Queue} wl_registry#2.global(4, "wl_compositor", 6)
[1185504.883] {Default Queue} wl_registry#2.global(5, "wl_subcompositor", 1)
[1185504.887] {Default Queue} wl_registry#2.global(6, "wl_data_device_manager", 3)
[1185504.891] {Default Queue} wl_registry#2.global(7, "zwp_primary_selection_device_manager_v1", 1)
[1185504.895] {Default Queue} wl_registry#2.global(8, "zwlr_data_control_manager_v1", 2)
[1185504.898] {Default Queue} wl_registry#2.global(9, "zwlr_output_manager_v1", 4)
[1185504.902] {Default Queue} wl_registry#2.global(10, "zwlr_output_power_manager_v1", 1)
[1185504.906] {Default Queue} wl_registry#2.global(11, "xdg_wm_base", 3)
[1185504.911] {Default Queue} wl_registry#2.global(12, "zwlr_layer_shell_v1", 4)
[1185504.914] {Default Queue} wl_registry#2.global(13, "xwayland_shell_v1", 1)
[1185504.919] {Default Queue} wl_registry#2.global(14, "zwp_tablet_manager_v2", 1)
[1185504.923] {Default Queue} wl_registry#2.global(15, "wl_seat", 8)
[1185504.927] {Default Queue} wl_registry#2.global(16, "zwlr_screencopy_manager_v1", 3)
[1185504.930] {Default Queue} wl_registry#2.global(17, "zwlr_gamma_control_manager_v1", 1)
[1185504.934] {Default Queue} wl_registry#2.global(18, "zwlr_export_dmabuf_manager_v1", 1)
[1185504.938] {Default Queue} wl_registry#2.global(19, "zxdg_output_manager_v1", 3)
[1185504.942] {Default Queue} wl_registry#2.global(20, "wp_drm_lease_device_v1", 1)
[1185504.946] {Default Queue} wl_registry#2.global(21, "zwlr_input_inhibit_manager_v1", 1)
[1185504.950] {Default Queue} wl_registry#2.global(22, "ext_idle_notifier_v1", 1)
[1185504.954] {Default Queue} wl_registry#2.global(23, "zwp_idle_inhibit_manager_v1", 1)
[1185504.958] {Default Queue} wl_registry#2.global(24, "org_kde_kwin_server_decoration_manager", 1)
[1185504.962] {Default Queue} wl_registry#2.global(25, "zxdg_decoration_manager_v1", 1)
[1185504.966] {Default Queue} wl_registry#2.global(26, "zwp_virtual_keyboard_manager_v1", 1)
[1185504.970] {Default Queue} wl_registry#2.global(27, "zwlr_virtual_pointer_manager_v1", 2)
[1185504.974] {Default Queue} wl_registry#2.global(28, "zwp_pointer_gestures_v1", 3)
[1185504.978] {Default Queue} wl_registry#2.global(29, "zwp_relative_pointer_manager_v1", 1)
[1185504.982] {Default Queue} wl_registry#2.global(30, "zwp_pointer_constraints_v1", 1)
[1185504.986] {Default Queue} wl_registry#2.global(31, "wp_presentation", 1)
[1185504.990] {Default Queue} wl_registry#2.global(32, "wp_viewporter", 1)
[1185504.994] {Default Queue} wl_registry#2.global(33, "zxdg_exporter_v1", 1)
[1185504.998] {Default Queue} wl_registry#2.global(34, "zxdg_importer_v1", 1)
[1185505.002] {Default Queue} wl_registry#2.global(35, "zxdg_exporter_v2", 1)
[1185505.006] {Default Queue} wl_registry#2.global(36, "zxdg_importer_v2", 1)
[1185505.010] {Default Queue} wl_registry#2.global(37, "wp_fractional_scale_manager_v1", 1)
[1185505.015] {Default Queue} wl_registry#2.global(38, "wp_single_pixel_buffer_manager_v1", 1)
[1185505.019] {Default Queue} wl_registry#2.global(39, "wl_output", 4)
[1185505.023] {Default Queue} wl_registry#2.global(40, "zwlr_foreign_toplevel_manager_v1", 3)
[1185505.027] {Default Queue} wl_registry#2.global(41, "wf_info_base", 1)
[1185505.031] {Default Queue}  -> wl_registry#2.bind(41, "wf_info_base", 1, new id [unknown]#4)
[1185505.036] {Default Queue} wl_callback#3.done(377)
[1185505.045] {Default Queue}  -> wf_info_base#4.view_info()
[1228494.903] discarded [unknown]#2.[event 1](0 fd, 12 byte)
[1228494.926] discarded [unknown]#2.[event 1](0 fd, 12 byte)
```
i'll try that QT app and report back.

**Comment by flexibeast** [comment]
Hmm, curiouser and curiouser. When i first ran the QT app, it opened a dialog which said "Click to get window information". Clicking on that resulted in various bits of information about that window. But when i've tried subsequently, although the "Click to get window information" dialog opens, clicking either on that text, or anywhere on the screen, results in the same semi-freeze i mentioned above, requiring me to terminate the Wayfire process.

**Comment by soreau** [comment]
I'm now starting to wonder, if wayfire is built with wlroots 0.18 from the track-wlroots branch or wf-info is built from its track-wlroots-0.18 branch. What is the output of:

`ldd "$(command -v wayfire)" | grep wlroots`

Also check the lib:

`ldd /usr/lib64/wayfire/libwf-info.so | grep wlroots`

**Comment by flexibeast** [comment]
```
$ ldd "$(command -v wayfire)" | grep wlroots  
	libwlroots.so.12 => /usr/lib64/libwlroots.so.12 (0x00007f90c6f99000)
$ ldd /usr/lib64/wayfire/libwf-info.so | grep wlroots
	libwlroots.so.12 => /usr/lib64/libwlroots.so.12 (0x00007ff9042bb000)
```
And then:
```
$ equery f wlroots-0.17.4 | grep libwlroots
/usr/lib64/libwlroots.so
/usr/lib64/libwlroots.so.12
$ equery f wlroots-0.18.0 | grep libwlroots
/usr/lib64/libwlroots-0.18.so
```

**Comment by soreau** [comment]
That looks fine. So it sounds like the pointer grab is the issue somehow. I don't think wf-info requires any other plugin to be enabled for it to work.. What happens if you simply try `wf-info -l` to list all views? I would think that should work unless there's a fundamental problem.

**Comment by flexibeast** [comment]
Yep, `wf-info -l` works without issues. 🙂

**Comment by soreau** [comment]
Well to let you know what happens and how wf-info works a bit (and even for my own rubber ducking), the plugin is initialized and waits for a call to get view information from the wayland socket. In the default case, it initiates a grab on the outputs and begins processing mouse button events, and ends the grab on any click. When the button is clicked, the grab is deactivated. I'm not sure why it would grab and then freeze, unless it was crashing and writing the backtrace when you kill it.

To debug, I'd first run wayfire -c /tmp/wayfire.ini in a running wayfire session so it runs nested, then try wf-info in the wayfire window and see if there's any interesting output in the terminal. If not, maybe put some LOGI() messages, especially in end_grab() and deactivate() [here](https://github.com/soreau/wf-info/blob/master/src/plugin/wayfire-information.cpp) to see if those are getting called at all.

**Comment by flexibeast** [comment]
Sorry i've taken so long to get to this; my health has been even worse than usual.

i copied /usr/share/wayfire/wayfire.ini to /tmp/wayfire.ini, changed the latter to run kitty instead of alacritty (which i don't have installed), and ran `wayfire -c /tmp/wayfire.ini` in a terminal. The nested session started up, and i pressed `<super> KEY_ENTER` to start kitty. This produced output in the 'outer' terminal:
```
II 17-10-24 13:20:10.714 - [wayfire-0.9.0/src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: kitty app-id: kitty
```
i then ran `wf-info` in kitty in the nested session, and again got the "Wayfire information protocol not advertised ..." message i mentioned above in the 'inner' terminal - but with no further output in the 'outer' terminal. :-(

i added `LOGI()` lines around and within `deactivate()`, rebuilt and reinstalled, check that the new binary was in place, and went through the above procedure again - none of the `LOGI()` messages were displayed.

**Comment by soreau** [comment]
It sounds like you need to add 'wf-info' to the list of [core] plugins in /tmp/wayfire.ini.

**Comment by flexibeast** [comment]
Ah, yeah, sorry. :woman_facepalming: 

Okay, so, with that done, the "Wayfire information protcol ..." message is no longer displayed, of course, but the rest of the output is unchanged - nothing after the "new surface" message. But the nested session is certainly freezing.

Also, fwiw: modifying the config file in some way to force a reload 'unfreezes' the session.

**Comment by soreau** [comment]
If you're using latest wayfire track-wlroots branch and wf-info track-wlroots-0.18 branch, can you try installing pywayfire and running [this script](https://github.com/soreau/wf-info/blob/track-wlroots-0.18/ipc-scripts/wf-info.py)? It uses a different method to get the data but the usage is basically the same.

**Comment by flexibeast** [comment]
Hmm, so i'm running Wayfire 0.9.0 via the Gentoo ebuild, built on wlroots 0.17.4 installed via the Gentoo ebuild. i was already building wf-info master. i'll try setting up pywayfire git now.

**Comment by flexibeast** [comment]
Okay, well, as it is i was having issues getting the script to run. i'm really not familiar with the Python ecosystem, so i'm probably doing something wrong. What i've done is:
```
$ git clone https://github.com/WayfireWM/pywayfire
$ cd pywayfire
$ python -m venv ~/python/pywayfire
$ . ~/python/pywayfire/bin/activate
$ pip3 install .
$ pip list
```
with the output of that last command being:
```
Package Version
------- -------
pip     24.2
wayfire 3.1
```
But:
```
~/Downloads/src/wf-info.py
Traceback (most recent call last):
  File "/home/alexis/Downloads/src/wf-info.py", line 4, in <module>
    from wayfire import WayfireSocket
ImportError: cannot import name 'WayfireSocket' from 'wayfire' (unknown location)
```

**Comment by soreau** [comment]
You might have to set `PYTHONPATH` to the directory ~/.local/lib/python-$ver/site-packages (or wherever wayfire was installed).

**Comment by flexibeast** [comment]
Okay, thanks. i rebuilt and reinstalled wf-info from the `freeze-fix-test` branch. i also added PYTHONPATH to the relevant venv path. i now get:
```
$ ~/Downloads/src/wf-info.py 
Traceback (most recent call last):
  File "/home/alexis/Downloads/src/wf-info.py", line 10, in <module>
    print(f"View Info:\n{json.dumps(wpe.get_view_info(), indent=2, ensure_ascii=False)}")
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/python/pywayfire/lib/python3.12/site-packages/wayfire/extra/wpe.py", line 100, in get_view_info
    return self.socket.send_json(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/python/pywayfire/lib/python3.12/site-packages/wayfire/ipc.py", line 290, in send_json
    response = self.read_message()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/python/pywayfire/lib/python3.12/site-packages/wayfire/ipc.py", line 65, in read_message
    raise Exception(f"Method {response['method']} is not available. \
                              ~~~~~~~~^^^^^^^^^^
KeyError: 'method'
```

**Comment by soreau** [comment]
I think you also need to add ipc and possibly ipc-rules plugins to your /tmp/wayfire.ini plugin list.

**Comment by flexibeast** [comment]
Hmm, no, this is happening under my 'main' WF session; i wanted to make sure it was working in general before trying in a nested session. In that session, both those plugins are already enabled.

**Comment by soreau** [comment]
Did you restart your main session since installing the freeze-fix-test wf-info branch? If not, you will need to, or test in the nested session first and if it works there, it should work after restarting the main session.

**Comment by flexibeast** [comment]
Oh okay. Well, in the nested session, wl-info.py doesn't report any errors; it just prints a newline and then the session freezes in the same manner as with the wl-info binary.

**Comment by soreau** [comment]
I'm guessing this was working at some point before so you know how to use it, but for the sake of completeness, I will say that after running wf-info or wf-info.py, the wf-info plugin is waiting for a click on a window. It should have a crosshair cursor until clicking somewhere. After the click, it should display the window information in the terminal.

If this doesn't work and the session is actually frozen, I the problem is deeper, though it's not clear exactly what might be happening. You can use 'WAYLAND_DEBUG=1 wf-info' or even strace to see where it's hanging. It might be useful to run wayfire nested and then in a terminal in the main session, run `WAYLAND_DISPLAY=wayland-2 WAYLAND_DEBUG=1 strace wf-info` and see where it stops.

**Comment by soreau** [comment]
@flexibeast Please open a new issue if you require further assistance. The original issue here is fixed, so closing for now.
